-- Supabase migration placeholder
-- Module: nuc_auth
-- Generated by: .config/bash/bootstrap-module-supabase-from-laravel.sh
-- TODO: replace this placeholder with real SQL converted from Laravel sources.
-- Source files:
-- - modules/nuc_auth/database/migrations/2014_10_12_100000_create_password_resets_table.php
-- - modules/nuc_auth/database/migrations/2014_10_12_100000_create_password_reset_tokens_table.php
-- - modules/nuc_auth/database/migrations/2019_12_14_000001_create_personal_access_tokens_table.php

select 'TODO: implement nuc_auth Supabase SQL' as message;
