create table if not exists public.friendships (
  id bigint generated by default as identity primary key,
  sender_id uuid references auth.users (id) on delete cascade,
  recipient_id uuid references auth.users (id) on delete cascade,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.friendships add column if not exists sender_id uuid references auth.users (id) on delete cascade;
alter table public.friendships add column if not exists recipient_id uuid references auth.users (id) on delete cascade;
alter table public.friendships add column if not exists status text not null default 'pending';
alter table public.friendships add column if not exists created_at timestamptz not null default now();
alter table public.friendships add column if not exists updated_at timestamptz not null default now();

create table if not exists public.friendship_groups (
  id bigint generated by default as identity primary key,
  friendship_id bigint not null references public.friendships (id) on delete cascade,
  friend_id uuid references auth.users (id) on delete cascade,
  friend_type text not null default 'user',
  group_id integer not null,
  unique(friendship_id, friend_id, friend_type, group_id)
);

alter table public.friendship_groups add column if not exists friendship_id bigint references public.friendships (id) on delete cascade;
alter table public.friendship_groups add column if not exists friend_id uuid references auth.users (id) on delete cascade;
alter table public.friendship_groups add column if not exists friend_type text not null default 'user';
alter table public.friendship_groups add column if not exists group_id integer;

create table if not exists public.interactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  subject_id text not null,
  subject_type text not null,
  relation text not null default 'follow',
  relation_value double precision,
  relation_type text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.interactions add column if not exists user_id uuid references auth.users (id) on delete cascade;
alter table public.interactions add column if not exists subject_id text;
alter table public.interactions add column if not exists subject_type text;
alter table public.interactions add column if not exists relation text not null default 'follow';
alter table public.interactions add column if not exists relation_value double precision;
alter table public.interactions add column if not exists relation_type text;
alter table public.interactions add column if not exists created_at timestamptz not null default now();
alter table public.interactions add column if not exists updated_at timestamptz not null default now();

alter table public.friendships enable row level security;
alter table public.friendship_groups enable row level security;
alter table public.interactions enable row level security;

drop policy if exists "friendships_authenticated_all" on public.friendships;
create policy "friendships_authenticated_all" on public.friendships for all to authenticated using (true) with check (true);
drop policy if exists "friendship_groups_authenticated_all" on public.friendship_groups;
create policy "friendship_groups_authenticated_all" on public.friendship_groups for all to authenticated using (true) with check (true);
drop policy if exists "interactions_authenticated_all" on public.interactions;
create policy "interactions_authenticated_all" on public.interactions for all to authenticated using (true) with check (true);
