create table if not exists public.share_requests (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references auth.users (id) on delete cascade,
  receiver_id uuid not null references auth.users (id) on delete cascade,
  entity_type text not null,
  entity_ids jsonb not null default '[]'::jsonb,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.share_requests add column if not exists sender_id uuid references auth.users (id) on delete cascade;
alter table public.share_requests add column if not exists receiver_id uuid references auth.users (id) on delete cascade;
alter table public.share_requests add column if not exists entity_type text;
alter table public.share_requests add column if not exists entity_ids jsonb not null default '[]'::jsonb;
alter table public.share_requests add column if not exists status text not null default 'pending';
alter table public.share_requests add column if not exists created_at timestamptz not null default now();
alter table public.share_requests add column if not exists updated_at timestamptz not null default now();

create index if not exists share_requests_receiver_status_idx on public.share_requests (receiver_id, status);
create index if not exists share_requests_sender_status_idx on public.share_requests (sender_id, status);

alter table public.share_requests enable row level security;
drop policy if exists "share_requests_authenticated_all" on public.share_requests;
create policy "share_requests_authenticated_all" on public.share_requests for all to authenticated using (true) with check (true);
